version: "3.8"

services:
  server:
    build: ./
    ports:
      - 3331:3331
    container_name: server-container
    volumes:
      - ./:/usr/app
    env_file:
      - .env
    networks:
      - rei-crm-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb_container
    networks:
      - rei-crm-network
    volumes:
      - mongoData:/data/db

networks:
  rei-crm-network:

volumes:
  mongoData:
